[build]
  base = "client"
  publish = "client/build"
  command = "npm run build"  # or the appropriate command for your frontend

# Uncomment and adjust if you're using serverless functions
# [build.environment]
#   NODE_VERSION = "16"

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
